/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package index;


/**
 *
 * @author Mochamad One
 */
//import package futsalapp;

import futsalapp.FutsalFrame;
import futsalapp.lihat_lapangan;

public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        menuLapangan = new javax.swing.JMenu();
        menuTambahLapangan = new javax.swing.JMenuItem();
        menuLihatLapangan = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        menuLapangan.setText("Lapangan");

        menuTambahLapangan.setText("Tambah Lapangan");
        menuTambahLapangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTambahLapanganActionPerformed(evt);
            }
        });
        menuLapangan.add(menuTambahLapangan);

        menuLihatLapangan.setText("Lihat Lapangan");
        menuLihatLapangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLihatLapanganActionPerformed(evt);
            }
        });
        menuLapangan.add(menuLihatLapangan);

        jMenuBar2.add(menuLapangan);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 383, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuTambahLapanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTambahLapanganActionPerformed
        // TODO add your handling code here:
    FutsalFrame form = new FutsalFrame();
    form.setLocationRelativeTo(this);
    form.setVisible(true);
    }//GEN-LAST:event_menuTambahLapanganActionPerformed

    private void menuLihatLapanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLihatLapanganActionPerformed
        // TODO add your handling code here:
    lihat_lapangan form = new lihat_lapangan();
    form.setLocationRelativeTo(this);
    form.setVisible(true);
    }//GEN-LAST:event_menuLihatLapanganActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu menuLapangan;
    private javax.swing.JMenuItem menuLihatLapangan;
    private javax.swing.JMenuItem menuTambahLapangan;
    // End of variables declaration//GEN-END:variables
}
