/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package futsalapp;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;


/**
 *
 * @author Mochamad One
 */
public class FutsalFrame extends javax.swing.JFrame {

    /**
     * Creates new form FutsalFrame
     */
    public FutsalFrame() {
        initComponents();
        textId.setEnabled(false); // ID otomatis dari database (Auto Increment)
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textNama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comboTipe = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comboStatus = new javax.swing.JComboBox<>();
        textHarga = new javax.swing.JTextField();
        buttonSimpan = new javax.swing.JButton();
        buttonEdit = new javax.swing.JButton();
        buttonBatal = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 420));

        jLabel1.setText("ID Lapangan:");

        textId.setEditable(false);
        textId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIdActionPerformed(evt);
            }
        });

        jLabel2.setText("Nama Lapangan:");

        jLabel3.setText("Tipe Lapangan:");

        comboTipe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indoor", "Outdoor" }));
        comboTipe.setSelectedIndex(-1);
        comboTipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipeActionPerformed(evt);
            }
        });

        jLabel4.setText("Harga:");

        jLabel5.setText("Status:");

        comboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tersedia", "Terpesan" }));
        comboStatus.setSelectedIndex(-1);
        comboStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboStatusActionPerformed(evt);
            }
        });

        buttonSimpan.setBackground(new java.awt.Color(76, 175, 80));
        buttonSimpan.setText("Simpan");
        buttonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanActionPerformed(evt);
            }
        });

        buttonEdit.setBackground(new java.awt.Color(0, 153, 255));
        buttonEdit.setText("Edit");
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });

        buttonBatal.setBackground(new java.awt.Color(153, 153, 153));
        buttonBatal.setText("Batal");
        buttonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBatalActionPerformed(evt);
            }
        });

        buttonHapus.setBackground(new java.awt.Color(255, 0, 0));
        buttonHapus.setText("Hapus");
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                        .addGap(378, 378, 378))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(textNama)
                                        .addComponent(textId, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                        .addComponent(textHarga)
                                        .addComponent(comboStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(comboTipe, 0, 144, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(buttonSimpan)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(171, 171, 171)
                                .addComponent(buttonBatal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textId, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textNama, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(comboTipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboStatus))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSimpan)
                    .addComponent(buttonEdit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonBatal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(147, 147, 147))
        );

        pack();
    }// </editor-fold>                        

    private void comboTipeActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void comboStatusActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        // 1. Ambil data dari form
        String namaLapangan = textNama.getText().trim();
    String tipeLapangan = (String) comboTipe.getSelectedItem();
    String hargaStr = textHarga.getText().trim();
        String status = (String) comboStatus.getSelectedItem();
        
        // 2. Validasi input kosong
    if (namaLapangan.isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "Nama Lapangan tidak boleh kosong!",
            "Peringatan",
            JOptionPane.WARNING_MESSAGE);
        textNama.requestFocus();
        return;
    }
    
    if (hargaStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Harga per jam tidak boleh kosong!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            textHarga.requestFocus();
            return;
        }
    
    // 3. Validasi angka untuk harga
    int hargaPerJam;
        try {
            hargaPerJam = Integer.parseInt(hargaStr);
            if (hargaPerJam <= 0) {
                JOptionPane.showMessageDialog(this, "Harga per jam harus lebih besar dari 0!", "Peringatan", JOptionPane.WARNING_MESSAGE);
                textHarga.requestFocus();
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Harga per jam harus berupa angka yang valid!", "Error", JOptionPane.ERROR_MESSAGE);
            textHarga.requestFocus();
            return;
        }
    
    
    // 4. Proses Simpan ke Database
    try {
            Connection koneksi = Koneksi.getKoneksi();
            if (koneksi == null) {
                JOptionPane.showMessageDialog(this, "Koneksi database gagal!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            String query = "INSERT INTO lapangan (nama_lapangan, tipe_lapangan, harga_per_jam, status) VALUES (?, ?, ?, ?)";
            PreparedStatement ps = koneksi.prepareStatement(query);
            ps.setString(1, namaLapangan);
            ps.setString(2, tipeLapangan);
            ps.setInt(3, hargaPerJam);
            ps.setString(4, status);
            
            int hasil = ps.executeUpdate();
            if (hasil > 0) {
                JOptionPane.showMessageDialog(this, "Data lapangan berhasil disimpan!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                
                // Reset form setelah berhasil simpan
                textNama.setText("");
                textHarga.setText("");
                comboTipe.setSelectedIndex(0);
                comboStatus.setSelectedIndex(0);
                textNama.requestFocus();
            }
            ps.close();
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error database: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    

    }                                            

    private void buttonBatalActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    textId.setText("");
    textNama.setText("");
    textHarga.setText("");
    comboTipe.setSelectedIndex(0);
    comboStatus.setSelectedIndex(0);
    textNama.requestFocus();
    }                                           

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    // Ambil data dari form
    String id = textId.getText().trim();
    String namaLapangan = textNama.getText().trim();
    String tipeLapangan = (String) comboTipe.getSelectedItem();
    String hargaStr = textHarga.getText().trim();
    String status = (String) comboStatus.getSelectedItem();

    // Validasi ID
    if (id.isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "Masukkan ID data yang ingin diedit!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Validasi nama
    if (namaLapangan.isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "Nama Lapangan tidak boleh kosong!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
        textNama.requestFocus();
        return;
    }

    // Validasi harga
    if (hargaStr.isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "Harga per jam tidak boleh kosong!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
        textHarga.requestFocus();
        return;
    }

    int hargaPerJam;

    try {
        hargaPerJam = Integer.parseInt(hargaStr);

        if (hargaPerJam <= 0) {
            JOptionPane.showMessageDialog(this,
                    "Harga per jam harus lebih besar dari 0!",
                    "Peringatan",
                    JOptionPane.WARNING_MESSAGE);
            textHarga.requestFocus();
            return;
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this,
                "Harga harus berupa angka!",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        textHarga.requestFocus();
        return;
    }

    // Konfirmasi edit
    int konfirmasi = JOptionPane.showConfirmDialog(
            this,
            "Apakah Anda yakin ingin mengubah data ini?",
            "Konfirmasi Edit",
            JOptionPane.YES_NO_OPTION
    );

    if (konfirmasi != JOptionPane.YES_OPTION) {
        return;
    }

    // Update database
    try {

        Connection koneksi = Koneksi.getKoneksi();

        if (koneksi == null) {
            JOptionPane.showMessageDialog(this,
                    "Koneksi database gagal!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        String query = "UPDATE lapangan SET "
                + "nama_lapangan = ?, "
                + "tipe_lapangan = ?, "
                + "harga_per_jam = ?, "
                + "status = ? "
                + "WHERE id = ?";

        PreparedStatement ps = koneksi.prepareStatement(query);

        ps.setString(1, namaLapangan);
        ps.setString(2, tipeLapangan);
        ps.setInt(3, hargaPerJam);
        ps.setString(4, status);
        ps.setInt(5, Integer.parseInt(id));

        int hasil = ps.executeUpdate();

        if (hasil > 0) {

            JOptionPane.showMessageDialog(this,
                    "Data berhasil diubah!",
                    "Sukses",
                    JOptionPane.INFORMATION_MESSAGE);

            // Reset form
            textId.setText("");
            textNama.setText("");
            textHarga.setText("");
            comboTipe.setSelectedIndex(0);
            comboStatus.setSelectedIndex(0);
            textNama.requestFocus();

        } else {

            JOptionPane.showMessageDialog(this,
                    "Data dengan ID tersebut tidak ditemukan!",
                    "Peringatan",
                    JOptionPane.WARNING_MESSAGE);
        }

        ps.close();

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(this,
                "Error database: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(this,
                "ID harus berupa angka!",
                "Error",
                JOptionPane.ERROR_MESSAGE);
    }
    }                                          

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
          String id = textId.getText().trim();

    // Validasi ID
    if (id.isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "Masukkan ID data yang ingin dihapus!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Konfirmasi hapus
    int konfirmasi = JOptionPane.showConfirmDialog(
            this,
            "Apakah Anda yakin ingin menghapus data dengan ID " + id + "?",
            "Konfirmasi Hapus",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
    );

    if (konfirmasi != JOptionPane.YES_OPTION) {
        return;
    }

    try {

        Connection koneksi = Koneksi.getKoneksi();

        if (koneksi == null) {
            JOptionPane.showMessageDialog(this,
                    "Koneksi database gagal!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        String query = "DELETE FROM lapangan WHERE id = ?";

        PreparedStatement ps = koneksi.prepareStatement(query);

        ps.setInt(1, Integer.parseInt(id));

        int hasil = ps.executeUpdate();

        if (hasil > 0) {

            JOptionPane.showMessageDialog(this,
                    "Data berhasil dihapus!",
                    "Sukses",
                    JOptionPane.INFORMATION_MESSAGE);

            // Reset form
            textId.setText("");
            textNama.setText("");
            textHarga.setText("");
            comboTipe.setSelectedIndex(0);
            comboStatus.setSelectedIndex(0);

            textNama.requestFocus();

        } else {

            JOptionPane.showMessageDialog(this,
                    "Data dengan ID tersebut tidak ditemukan!",
                    "Peringatan",
                    JOptionPane.WARNING_MESSAGE);
        }

        ps.close();

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(this,
                "Error database: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(this,
                "ID harus berupa angka!",
                "Error",
                JOptionPane.ERROR_MESSAGE);
    }
    }                                           

    private void textIdActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FutsalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FutsalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FutsalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FutsalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FutsalFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton buttonBatal;
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JComboBox<String> comboStatus;
    private javax.swing.JComboBox<String> comboTipe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField textHarga;
    private javax.swing.JTextField textId;
    private javax.swing.JTextField textNama;
    // End of variables declaration                   

}
