/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


package futsalapp;

import index.home;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.Desktop;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

import java.nio.file.Files;
import java.util.Base64;

/**
 *
 * @author Mochamad One
 */
public class lihat_lapangan extends javax.swing.JFrame {

    /**
     * Creates new form lihat_lapangan
     */
    public lihat_lapangan() {
           initComponents();
    tampilDataLapangan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        textNama = new javax.swing.JTextField();
        textHarga = new javax.swing.JTextField();
        comboTipe = new javax.swing.JComboBox<>();
        comboStatus = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Tipe Lapangan", "Harga Perjam", "Status"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setBackground(new java.awt.Color(0, 102, 255));
        jButton1.setText("Cetak");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        comboTipe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indoor", "OutDoor" }));
        comboTipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipeActionPerformed(evt);
            }
        });

        comboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tersedia", "Terpesan" }));

        jLabel1.setText("Nama Lapangan");

        jLabel2.setText("Tipe Lapangan");

        jLabel3.setText("Harga Perjam");

        jLabel4.setText("Status");

        btnSimpan.setBackground(new java.awt.Color(51, 255, 0));
        btnSimpan.setText("Tambah");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(0, 153, 204));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(102, 102, 102));
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(255, 0, 0));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(153, 153, 0));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textNama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboTipe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textHarga, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSimpan)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit)
                        .addGap(18, 18, 18)
                        .addComponent(btnReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHapus)))
                .addContainerGap(440, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNama, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboTipe, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnEdit)
                    .addComponent(btnReset)
                    .addComponent(btnHapus))
                .addContainerGap(237, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        6. Cetak
 Connection koneksi = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    FileWriter writer = null;

    try {

        // =========================================
        // KONEKSI DATABASE
        // =========================================
        koneksi = Koneksi.getKoneksi();

        String query = "SELECT id, nama_lapangan, tipe_lapangan, "
                + "harga_per_jam, status "
                + "FROM lapangan ORDER BY id";

        ps = koneksi.prepareStatement(query);
        rs = ps.executeQuery();

        // =========================================
        // MEMBACA LOGO
        // =========================================
        String logoBase64 = "";

        File logoFile = new File("src/futsalapp/logo_unpam.jpg");

        if (logoFile.exists()) {

            byte[] logoBytes = Files.readAllBytes(
                    logoFile.toPath()
            );

            logoBase64 = Base64.getEncoder()
                    .encodeToString(logoBytes);
        }

        // =========================================
        // FILE HTML
        // =========================================
        File file = File.createTempFile(
                "laporan_lapangan_",
                ".html"
        );

        writer = new FileWriter(file);

        // =========================================
        // HTML
        // =========================================

        writer.write("<!DOCTYPE html>");
        writer.write("<html lang='id'>");

        writer.write("<head>");

        writer.write("<meta charset='UTF-8'>");

        writer.write("<meta name='viewport' "
                + "content='width=device-width, initial-scale=1.0'>");

        writer.write("<title>Laporan Data Lapangan Futsal</title>");

        // =========================================
        // CSS MODERN
        // =========================================

        writer.write("<style>");

        writer.write("* {");
        writer.write("box-sizing: border-box;");
        writer.write("}");

        writer.write("body {");
        writer.write("margin: 0;");
        writer.write("padding: 30px;");
        writer.write("font-family: 'Segoe UI', Arial, sans-serif;");
        writer.write("background: #f1f5f9;");
        writer.write("color: #1e293b;");
        writer.write("}");

        writer.write(".container {");
        writer.write("max-width: 1100px;");
        writer.write("margin: auto;");
        writer.write("}");

        // HEADER

        writer.write(".header {");
        writer.write("background: linear-gradient(135deg, #0f172a, #1e40af);");
        writer.write("border-radius: 20px;");
        writer.write("padding: 30px;");
        writer.write("color: white;");
        writer.write("display: flex;");
        writer.write("align-items: center;");
        writer.write("justify-content: space-between;");
        writer.write("box-shadow: 0 10px 30px rgba(15,23,42,.20);");
        writer.write("}");

        writer.write(".brand {");
        writer.write("display: flex;");
        writer.write("align-items: center;");
        writer.write("gap: 20px;");
        writer.write("}");

        writer.write(".logo {");
        writer.write("width: 75px;");
        writer.write("height: 75px;");
        writer.write("object-fit: contain;");
        writer.write("background: white;");
        writer.write("border-radius: 15px;");
        writer.write("padding: 8px;");
        writer.write("}");

        writer.write(".title h1 {");
        writer.write("margin: 0;");
        writer.write("font-size: 28px;");
        writer.write("}");

        writer.write(".title p {");
        writer.write("margin: 7px 0 0;");
        writer.write("color: #cbd5e1;");
        writer.write("}");

        // PRINT BUTTON

        writer.write(".print-button {");
        writer.write("border: none;");
        writer.write("background: white;");
        writer.write("color: #1e40af;");
        writer.write("padding: 12px 20px;");
        writer.write("border-radius: 10px;");
        writer.write("font-size: 14px;");
        writer.write("font-weight: bold;");
        writer.write("cursor: pointer;");
        writer.write("transition: .2s;");
        writer.write("}");

        writer.write(".print-button:hover {");
        writer.write("background: #dbeafe;");
        writer.write("transform: translateY(-2px);");
        writer.write("}");

        // CARD

        writer.write(".card {");
        writer.write("background: white;");
        writer.write("margin-top: 25px;");
        writer.write("border-radius: 18px;");
        writer.write("padding: 25px;");
        writer.write("box-shadow: 0 8px 25px rgba(15,23,42,.08);");
        writer.write("}");

        writer.write(".section-title {");
        writer.write("font-size: 20px;");
        writer.write("font-weight: 700;");
        writer.write("margin-bottom: 20px;");
        writer.write("}");

        // TABLE

        writer.write("table {");
        writer.write("width: 100%;");
        writer.write("border-collapse: separate;");
        writer.write("border-spacing: 0;");
        writer.write("overflow: hidden;");
        writer.write("border: 1px solid #e2e8f0;");
        writer.write("border-radius: 12px;");
        writer.write("}");

        writer.write("th {");
        writer.write("background: #f8fafc;");
        writer.write("color: #475569;");
        writer.write("font-size: 13px;");
        writer.write("text-transform: uppercase;");
        writer.write("letter-spacing: .5px;");
        writer.write("padding: 15px;");
        writer.write("text-align: left;");
        writer.write("border-bottom: 1px solid #e2e8f0;");
        writer.write("}");

        writer.write("td {");
        writer.write("padding: 15px;");
        writer.write("border-bottom: 1px solid #e2e8f0;");
        writer.write("}");

        writer.write("tr:last-child td {");
        writer.write("border-bottom: none;");
        writer.write("}");

        writer.write("tbody tr:hover {");
        writer.write("background: #f8fafc;");
        writer.write("}");

        // BADGE

        writer.write(".badge {");
        writer.write("display: inline-block;");
        writer.write("padding: 6px 12px;");
        writer.write("border-radius: 999px;");
        writer.write("font-size: 12px;");
        writer.write("font-weight: 600;");
        writer.write("}");

        writer.write(".tersedia {");
        writer.write("background: #dcfce7;");
        writer.write("color: #166534;");
        writer.write("}");

        writer.write(".terpesan {");
        writer.write("background: #fee2e2;");
        writer.write("color: #991b1b;");
        writer.write("}");

        // FOOTER

        writer.write(".footer {");
        writer.write("text-align: center;");
        writer.write("margin-top: 25px;");
        writer.write("font-size: 13px;");
        writer.write("color: #64748b;");
        writer.write("}");

        // RESPONSIVE

        writer.write("@media(max-width: 700px) {");

        writer.write("body {");
        writer.write("padding: 15px;");
        writer.write("}");

        writer.write(".header {");
        writer.write("flex-direction: column;");
        writer.write("align-items: flex-start;");
        writer.write("gap: 20px;");
        writer.write("}");

        writer.write("table {");
        writer.write("font-size: 12px;");
        writer.write("}");

        writer.write("th, td {");
        writer.write("padding: 9px;");
        writer.write("}");

        writer.write("}");

        // PRINT STYLE

        writer.write("@media print {");

        writer.write("body {");
        writer.write("background: white;");
        writer.write("padding: 0;");
        writer.write("}");

        writer.write(".container {");
        writer.write("max-width: 100%;");
        writer.write("}");

        writer.write(".header {");
        writer.write("box-shadow: none;");
        writer.write("}");

        writer.write(".print-button {");
        writer.write("display: none;");
        writer.write("}");

        writer.write(".card {");
        writer.write("box-shadow: none;");
        writer.write("}");

        writer.write("}");

        writer.write("</style>");

        writer.write("</head>");

        writer.write("<body>");

        writer.write("<div class='container'>");

        // =========================================
        // HEADER
        // =========================================

        writer.write("<div class='header'>");

        writer.write("<div class='brand'>");

        if (!logoBase64.isEmpty()) {

            writer.write(
                    "<img class='logo' "
                    + "src='data:image/png;base64,"
                    + logoBase64
                    + "'>"
            );

        } else {

            writer.write(
                    "<div class='logo' "
                    + "style='display:flex;"
                    + "align-items:center;"
                    + "justify-content:center;"
                    + "font-size:30px;'>"
                    + "⚽"
                    + "</div>"
            );
        }

        writer.write("<div class='title'>");

        writer.write("<h1>Data Lapangan Futsal</h1>");

        writer.write(
                "<p>Laporan informasi lapangan futsal</p>"
        );

        writer.write("</div>");

        writer.write("</div>");

        // PRINT BUTTON

        writer.write(
                "<button class='print-button' "
                + "onclick='window.print()'>"
                + "🖨 Cetak / Print"
                + "</button>"
        );

        writer.write("</div>");

        // =========================================
        // TABLE CARD
        // =========================================

        writer.write("<div class='card'>");

        writer.write(
                "<div class='section-title'>"
                + "Daftar Lapangan"
                + "</div>"
        );

        writer.write("<table>");

        writer.write("<thead>");

        writer.write("<tr>");

        writer.write("<th>ID</th>");
        writer.write("<th>Nama Lapangan</th>");
        writer.write("<th>Tipe Lapangan</th>");
        writer.write("<th>Harga / Jam</th>");
        writer.write("<th>Status</th>");

        writer.write("</tr>");

        writer.write("</thead>");

        writer.write("<tbody>");

        // =========================================
        // DATA DATABASE
        // =========================================

        while (rs.next()) {

            int id = rs.getInt("id");

            String nama = rs.getString("nama_lapangan");

            String tipe = rs.getString("tipe_lapangan");

            int harga = rs.getInt("harga_per_jam");

            String status = rs.getString("status");

            String classStatus = "";

            if (status.equalsIgnoreCase("Tersedia")) {
                classStatus = "tersedia";
            } else {
                classStatus = "terpesan";
            }

            writer.write("<tr>");

            writer.write(
                    "<td><strong>"
                    + id
                    + "</strong></td>"
            );

            writer.write(
                    "<td>"
                    + nama
                    + "</td>"
            );

            writer.write(
                    "<td>"
                    + tipe
                    + "</td>"
            );

            writer.write(
                    "<td><strong>Rp "
                    + String.format("%,d", harga)
                    + "</strong></td>"
            );

            writer.write(
                    "<td>"
                    + "<span class='badge "
                    + classStatus
                    + "'>"
                    + status
                    + "</span>"
                    + "</td>"
            );

            writer.write("</tr>");
        }

        writer.write("</tbody>");

        writer.write("</table>");

        writer.write("</div>");

        // =========================================
        // FOOTER
        // =========================================

        writer.write(
                "<div class='footer'>"
                + "Laporan Data Lapangan Futsal"
                + " &bull; by FutsalApp 😎"
                + "</div>"
        );

        writer.write("</div>");

        writer.write("</body>");

        writer.write("</html>");

        writer.close();

        // =========================================
        // BUKA HTML DI BROWSER
        // =========================================

        Desktop.getDesktop().browse(file.toURI());

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(
                this,
                "Database Error: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
        );

    } catch (IOException e) {

        JOptionPane.showMessageDialog(
                this,
                "Gagal membuat laporan: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
        );

    } finally {

        try {
            if (rs != null) {
                rs.close();
            }

            if (ps != null) {
                ps.close();
            }

            if (koneksi != null) {
                koneksi.close();
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    }//GEN-LAST:event_jButton1ActionPerformed

    // ==========================================
// 1. EVENT KLIK TABEL (Pilih Data)
// ==========================================
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int baris = jTable1.getSelectedRow();
    if (baris != -1) {
        String nama = jTable1.getValueAt(baris, 1).toString();
        String tipe = jTable1.getValueAt(baris, 2).toString();
        String harga = jTable1.getValueAt(baris, 3).toString();
        String status = jTable1.getValueAt(baris, 4).toString();

        textNama.setText(nama);
        textHarga.setText(harga);
        comboTipe.setSelectedItem(tipe);
        comboStatus.setSelectedItem(status);
    }
}



private void resetForm() {
    textNama.setText("");
    textHarga.setText("");
    comboTipe.setSelectedIndex(0);
    comboStatus.setSelectedIndex(0);
    jTable1.clearSelection();
    }//GEN-LAST:event_jTable1MouseClicked

// ==========================================
// 2. TOMBOL SIMPAN / TAMBAH DATA (CREATE)
// ==========================================
    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        try {
        String nama = textNama.getText();
        String tipe = comboTipe.getSelectedItem().toString();
        String harga = textHarga.getText();
        String status = comboStatus.getSelectedItem().toString();

        if (nama.isEmpty() || harga.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Harap isi semua bidang!");
            return;
        }

        Connection conn = Koneksi.getKoneksi();
        // PERBAIKAN: Gunakan tipe_lapangan dan harga_per_jam
        String sql = "INSERT INTO lapangan (nama_lapangan, tipe_lapangan, harga_per_jam, status) VALUES (?, ?, ?, ?)";
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, nama);
        pst.setString(2, tipe);
        pst.setInt(3, Integer.parseInt(harga));
        pst.setString(4, status);
        
        pst.executeUpdate();
        JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");
        
        tampilDataLapangan(); // Refresh tabel
        resetForm();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal menyimpan data: " + e.getMessage());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Format harga harus berupa angka!");
    }
    }//GEN-LAST:event_btnSimpanActionPerformed

    // ==========================================
// 3. TOMBOL EDIT / UPDATE DATA (UPDATE)
// ==========================================
    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
       int baris = jTable1.getSelectedRow();
    if (baris == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data pada tabel yang ingin diubah!");
        return;
    }

    try {
        // Mengambil ID dari kolom 0
        String id = jTable1.getValueAt(baris, 0).toString();
        String nama = textNama.getText();
        String tipe = comboTipe.getSelectedItem().toString(); // Mengambil nilai dari ComboBox
        String harga = textHarga.getText();
        String status = comboStatus.getSelectedItem().toString();

        Connection conn = Koneksi.getKoneksi();
        // PERBAIKAN: Gunakan tipe_lapangan, harga_per_jam, dan id
        String sql = "UPDATE lapangan SET nama_lapangan=?, tipe_lapangan=?, harga_per_jam=?, status=? WHERE id=?";
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, nama);
        pst.setString(2, tipe);
        pst.setInt(3, Integer.parseInt(harga));
        pst.setString(4, status);
        pst.setInt(5, Integer.parseInt(id));

        pst.executeUpdate();
        JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!");

        tampilDataLapangan(); // Refresh tabel
        resetForm();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal memperbarui data: " + e.getMessage());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Format harga atau ID harus berupa angka!");
    }
        
    }//GEN-LAST:event_btnEditActionPerformed

    // ==========================================
// 5. TOMBOL RESET / CLEAR FORM
// ==========================================
    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        resetForm();
        
    }//GEN-LAST:event_btnResetActionPerformed

    
    

// ==========================================
// 4. TOMBOL HAPUS DATA (DELETE)
// ==========================================
    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int baris = jTable1.getSelectedRow();
    if (baris == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data pada tabel yang ingin dihapus!");
        return;
    }

    int konfirmasi = JOptionPane.showConfirmDialog(this, 
            "Apakah Anda yakin ingin menghapus data ini?", 
            "Konfirmasi Hapus", 
            JOptionPane.YES_NO_OPTION);

    if (konfirmasi == JOptionPane.YES_OPTION) {
        try {
            String idLapangan = jTable1.getValueAt(baris, 0).toString();

            Connection conn = Koneksi.getKoneksi();
            String sql = "DELETE FROM lapangan WHERE id=?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, idLapangan);

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");

            tampilDataLapangan(); // Refresh tabel
            resetForm();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal menghapus data: " + e.getMessage());
        }
    }
        
    }//GEN-LAST:event_btnHapusActionPerformed

    
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
   new home().setVisible(true); // Membuka menu utama home.java
    this.dispose();              // Menutup form lihat_lapangan
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void comboTipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_comboTipeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lihat_lapangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lihat_lapangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lihat_lapangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lihat_lapangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lihat_lapangan().setVisible(true);
            }
        });
    }
    
//    5. Method tampil data lapangan 

private void tampilDataLapangan() {

    DefaultTableModel model = new DefaultTableModel();

    model.addColumn("ID");
    model.addColumn("Nama Lapangan");
    model.addColumn("Tipe Lapangan");
    model.addColumn("Harga/Jam");
    model.addColumn("Status");

    try {
        Connection koneksi = Koneksi.getKoneksi();

        String query = "SELECT id, nama_lapangan, tipe_lapangan, "
                     + "harga_per_jam, status "
                     + "FROM lapangan "
                     + "ORDER BY id";

        PreparedStatement ps = koneksi.prepareStatement(query);
        ResultSet rs = ps.executeQuery();

        while (rs.next()) {

            model.addRow(new Object[]{
                rs.getInt("id"),
                rs.getString("nama_lapangan"),
                rs.getString("tipe_lapangan"),
                rs.getInt("harga_per_jam"),
                rs.getString("status")
            });
        }

        jTable1.setModel(model);

        rs.close();
        ps.close();

    } catch (SQLException e) {

        JOptionPane.showMessageDialog(
            this,
            "Gagal menampilkan data: " + e.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE
        );
    }
}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> comboStatus;
    private javax.swing.JComboBox<String> comboTipe;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField textHarga;
    private javax.swing.JTextField textNama;
    // End of variables declaration//GEN-END:variables
}
